exclude: [ 'LICENSE.txt', 'Rakefile' ]
highlighter: rouge
markdown: kramdown
paginate: 10
permalink: /:year/:month/:day/:title.html
excerpt_separator: <!--more-->

sass:
    sass_dir: assets/css
    style: compressed

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate

info:
    title: InspIRCd
    slogan: The Stable, High-Performance and Modular IRCd
    uri: http://www.inspircd.org

meta:
    description: InspIRCd Internet Relay Chat Daemon is a modular, high performance IRC daemon combining stability and a rich and extensive C++ API with optional features such as SSL and permanent channels.
    keywords: inspircd, ircd, internet relay chat

navigation:
    - title: Home
      uri: /
      icon: fa-home
    - title: Downloads
      uri: https://github.com/inspircd/inspircd/releases/latest
      target: _blank
      icon: fa-cloud-download
    - title: Documentation
      uri: https://docs.inspircd.org
      target: _blank
      icon: fa-book
    - title: Issue Tracker
      uri: https://github.com/inspircd/inspircd/issues
      target: _blank
      icon: fa-bug
    - title: InspIRCd API
      uri: /api
      target: _blank
      icon: fa-code
    - title: Follow us on GitHub
      uri: https://github.com/inspircd
      target: _blank
      icon: fa-github
    - title: Get InspIRCd
      uri: https://github.com/inspircd/inspircd/releases/latest
      target: _blank
      icon: fa-download

misc:
# theme: red {default} | green | blue
    theme: red
    currentVersion: 2.0.27
    gitHubUrl: https://github.com/inspircd
    latestUrl: https://github.com/inspircd/inspircd/releases/latest
    configGuideUrl: https://docs.inspircd.org/3/configuration
    installGuideUrl: https://docs.inspircd.org/3/installation
    devurl:
